### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Rm1n90** [Joeclinton1/google-images-download#20] opened 2022-07-27 11:55 UTC
Hi @Joeclinton1, Thanks for keeping the repo alive :) 
Im trying to download 500 images but getting the following error:
```
Traceback (most recent call last):
  File "/home/Documents/google-images-download/download_google_images.py", line 6, in <module>
    paths = response.download(arguments)   #passing the arguments to the function
  File "/home/Documents/google-images-download/google_images_download/google_images_download.py", line 946, in download
    paths, errors = self.download_executor(arguments)
  File "/home/Documents/google-images-download/google_images_download/google_images_download.py", line 1085, in download_executor
    images, tabs = self.download_extended_page(url, arguments['chromedriver'])
  File "/home/Documents/google-images-download/google_images_download/google_images_download.py", line 313, in download_extended_page
    images = self._image_objects_from_pack(self._extract_data_pack_extended(source))
  File "/home/Documents/google-images-download/google_images_download/google_images_download.py", line 199, in _image_objects_from_pack
    image_objects = json.loads(data)[31][-1][12][2]
  File "/home/anaconda3/envs/analytics/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/anaconda3/envs/analytics/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/anaconda3/envs/analytics/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I tried your fork as well but no success. Do you have any idea how can I solve it?

Thanks!!

**Comment by Tarik37** [comment] 2022-08-16 08:23
Hi @Joeclinton1, thanks for your patch,
I am having the same issue, everythings working fine when limit is set to 100, but broken past that
````
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
````

**Comment by tejasa97** [comment] 2022-08-17 11:43
Hi, can you share the exact command you're trying out? I will try to reproduce the issue and fix it @Tarik37 @Rm1n90

**Comment by Joeclinton1** [comment] 2022-08-18 09:58
@Rm1n90 I was able to recreate the problem when downloading more than 100 images. I expect google has changed the formatting of the response once again, i'll see if I can fix it.

**Comment by Joeclinton1** [comment] 2022-08-18 10:00
@tejasa97 
<img width="227" alt="image" src="https://user-images.githubusercontent.com/48254978/185368366-813403c0-2245-4951-a8cc-36a009e1e2c3.png">
I recreated it using these arguments in the test_google_images_download file.

**Comment by Joeclinton1** [comment] 2022-08-18 10:51
<img width="266" alt="image" src="https://user-images.githubusercontent.com/48254978/185382611-7fad888c-a65f-4a3d-8b3c-1f5974b47efd.png">

The bug is that chromium is being redirected to the "continue to google" page which obviously has no images. I will try to figure out why it suddenly changed behaviour. One solution though might be just clicking the "accept all" button.

**Comment by Joeclinton1** [comment] 2022-08-18 12:22
@Rm1n90 @Tarik37 I have merged a fix for this issue, please tell me if the issue is resolved and I can close this issue. :)

**Comment by tejasa97** [comment] 2022-08-19 06:12
@Joeclinton1 hey can i get in touch with you? have some interesting ideas :)

**Comment by Joeclinton1** [comment] 2022-08-20 10:38
@tejasa97 I'm not working on improving google-images-download at the moment unfortunately, just trying to fix the issues when they come up. If you have any suggestions, creating an issue for them would be the way to do it.

**Closed as completed** 2024-08-20 20:28 UTC
